"""projects_to_show to int

Revision ID: 2eba475f416b
Revises: 46ec4000378f
Create Date: 2023-10-20 00:43:48.423707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2eba475f416b'
down_revision = '46ec4000378f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users ALTER COLUMN projects_to_show TYPE integer[] USING projects_to_show::integer[]")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users ALTER COLUMN projects_to_show TYPE text[] USING projects_to_show::text[]")
    # ### end Alembic commands ###
