"""Change achievements to list

Revision ID: 3adb4ba4476d
Revises: 8460f7e14493
Create Date: 2023-09-10 14:54:33.169122

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3adb4ba4476d'
down_revision = '8460f7e14493'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE projects ALTER COLUMN achievements TYPE VARCHAR[] USING array[achievements]::VARCHAR[]')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE projects ALTER COLUMN achievements TYPE VARCHAR USING coalesce(achievements[1],'')")
    # ### end Alembic commands ###
