"""empty message

Revision ID: 59f4628e0ce2
Revises: 6b2c3e6d3224
Create Date: 2023-09-06 23:58:10.273314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59f4628e0ce2'
down_revision = '6b2c3e6d3224'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'images',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('projects', 'team',
               existing_type=postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
               nullable=True)
    op.add_column('users', sa.Column('projects', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'projects')
    op.alter_column('projects', 'team',
               existing_type=postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
               nullable=False)
    op.alter_column('projects', 'images',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    # ### end Alembic commands ###
