"""empty message

Revision ID: 8460f7e14493
Revises: 59f4628e0ce2
Create Date: 2023-09-07 01:33:13.160675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8460f7e14493'
down_revision = '59f4628e0ce2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('projects_requests', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('projects_responses', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'projects_responses')
    op.drop_column('users', 'projects_requests')
    # ### end Alembic commands ###
